import Head from 'next/head'

export default function Home({data}) {
  console.log(data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div>
        {data.map(m => (
          <div key={m._id}>
            <h1>{m.nombre}</h1>
            <span>{m.email}</span>
            <p>
              <span>{m.password}</span>
            </p>
          </div>
        ))}
      </div>
    
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`https://next-api-mongo.vercel.app/api/user`)
  const data = await res.json()

  return {
    props: {data}, // will be passed to the page component as props
  }
}